### ISSUE TITLE
Make a game using the random cards

### ISSUE THREAD

**Issue by kbielaski** [UCSB-CS56-Projects/cs56-games-dealer#17]
300-500 (depending on the game)

**Comment by ttstarck** [comment]
Using the Deck and Hand classes, all that would need to be done is making the actual game and then the interface to the game.

**Comment by hannavigil** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (300 pts)

**Comment by athielk** [comment]
black jack made.

**Comment by YunSuk** [comment]
F17 OK (300-500 points)
