### ISSUE TITLE
Make the ActionListeners in GamesDealerPanel.java into inner classes

### ISSUE THREAD

**Issue by kbielaski** [UCSB-CS56-Projects/cs56-games-dealer#18]
150

**Comment by ttstarck** [comment]
As of now, the ActionListener classes are written inside the parameters of a function call, which is hard to understand at first. Moving them out of the parameter and into an inner class would make the code more readable.

**Comment by hannavigil** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (150 pts)
