### ISSUE TITLE
Add a bet system

### ISSUE THREAD

**Issue by kpoon1** [UCSB-CS56-Projects/cs56-games-dealer#34]
Add a bet system that is applicable for BlackJack game.
It would be great if the bet system could also be applicable for future card games.

**Comment by athielk** [comment]
F16 OK (100pts)

**Comment by YunSuk** [comment]
User starts out with 10 points. User can bet x points (0<= x <= total points remaining) to earn or lose x points upon winning or losing.

**Comment by YunSuk** [comment]
This was only implemented in CLI. GUI version is not implemented.
