### ISSUE TITLE
Refactor this repo with games-blackjack and games-poker repos

### ISSUE THREAD

**Issue by SungKiwan** [ucsb-cs56-projects/cs56-games-dealer#51]
Take a look at the cs56-games-poker and cs56-games-blackjack repos. Analyze them and refactor the entire codes in this repo in such a way that cs56-games-dealer can be used as a library for "dealing cards" for these games.

**Comment by pconrad** [comment]
(F17 ok, W18 ok 500 pts)

**Comment by seemantasaha** [comment]
Partially resolved.
